---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.21.0
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "18,48"
              DOMAIN: "https://rss.${SECRET_DOMAIN}/"
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        existingClaim: freshrss-config
        globalMounts:
          - path: /var/www/FreshRSS/data
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
