---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.21.0
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "18,48"
              DOMAIN: "https://rss.${SECRET_DOMAIN}/"
      fivefilters-full-text-rss:
        containers:
          main:
            image:
              repository: heussd/fivefilters-full-text-rss
              tag: latest@sha256:c818379c7d1174048c1932a7b43b013ea2fdf481e8ef3694f94ab749d11f397f
              pullPolicy: IfNotPresent
            env_from:
              - secretRef:
                  name: freshrss-secret
    service:
      main:
        ports:
          http:
            port: 80
      second:
        controller: fivefilters-full-text-rss
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "rss.${SECRET_DOMAIN}"
      second:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:rss
          hajimari.io/appName: "FTR"
        hosts:
          - host: &host "rss-ftr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: second
                  port: http
        tls:
          - hosts:
              - "rss-ftr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: freshrss-config
        advancedMounts:
          main:
            main:
              - path: /var/www/FreshRSS/data
      cache:
        enabled: true
        existingClaim: freshrss-config-ftr
        advancedMounts:
          fivefilters-full-text-rss:
            main:
              - path: /var/www/html/cache
