# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          freshrss:
            image:
              repository: freshrss/freshrss
              tag: 1.27.0
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              CRON_MIN: "18,48"
              DOMAIN: "https://rss.${SECRET_DOMAIN}/"
      fivefilters-full-text-rss:
        containers:
          fivefilters-full-text-rss:
            image:
              repository: heussd/fivefilters-full-text-rss
              tag: latest@sha256:11bb0f136196e39a424bb1087530677631bd052edffeb661c355c023b5f72c83
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: freshrss-secret
    service:
      freshrss:
        controller: freshrss
        ports:
          http:
            port: 80
      fivefilters-full-text-rss:
        controller: fivefilters-full-text-rss
        ports:
          http:
            port: 80
    ingress:
      freshrss:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: freshrss
                  port: http
        tls:
          - hosts:
              - *host
      fivefilters-full-text-rss:
        className: internal
        annotations:
          hajimari.io/icon: mdi:rss
          hajimari.io/appName: "FTR"
        hosts:
          - host: "rss-ftr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: fivefilters-full-text-rss
                  port: http
        tls:
          - hosts:
              - "rss-ftr.${SECRET_DOMAIN}"
    persistence:
      config:
        existingClaim: freshrss-config
        advancedMounts:
          freshrss:
            freshrss:
              - path: /var/www/FreshRSS/data
      cache:
        existingClaim: freshrss-config-ftr
        advancedMounts:
          fivefilters-full-text-rss:
            fivefilters-full-text-rss:
              - path: /var/www/html/cache
