# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          vaultwarden:
            image:
              repository: vaultwarden/server
              tag: 1.31.0
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              DATA_FOLDER: "config"
              DOMAIN: https://vault.${SECRET_DOMAIN}
              SIGNUPS_ALLOWED: false
              WEBSOCKET_ENABLED: true
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_PORT: 3012
              SHOW_PASSWORD_HINT: false
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
    service:
      vaultwarden:
        controller: main
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
    ingress:
      vaultwarden:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:vaultwarden
        className: external
        hosts:
          - host: &host "vault.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: vaultwarden
                  port: http
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  identifier: vaultwarden
                  port: http
              - path: /notifications/hub
                pathType: Prefix
                service:
                  identifier: vaultwarden
                  port: websocket
        tls:
          - hosts:
            - *host
    persistence:
      config:
        existingClaim: vaultwarden-config
    defaultPodOptions:
      annotations:
        secret.reloader.stakater.com/reload: "vaultwarden"
