---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name vaultwarden
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-apps
