---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-4
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  bootstrap:
    recovery:
      source: &previous-cluster postgres-v3 #This must match backup.barmanObjectStore.serverName from previous backup
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: &dest-path s3://postgresql-data/
      endpointURL: &endpoint-url ${AWS_ENDPOINTS}
      serverName: postgres-v4 #This must increment when bootstrapping. You cannot have this be the same as the bootstrap version
      s3Credentials: &s3-creds
        accessKeyId:
          name: longhorn-backup-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: longhorn-backup-secret
          key: AWS_SECRET_ACCESS_KEY
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previous-cluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: *dest-path
        endpointURL: *endpoint-url
        s3Credentials: *s3-creds
