---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-data
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-apps
  resources:
    requests:
      storage: 1G
