apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-secret
    namespace: default
stringData:
    #ENC[AES256_GCM,data:bxohrS2/rpE8snuWJMM=,iv:z+KGwy00HTyW1Ybfozs0XkTBjejvUUwzC6zgkXt4Qy0=,tag:fi1S8GaTCVt6bJQxvAp70A==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cOQZhIdvVPMNUw==,iv:yGLf9kh7NP3CuYMuHeRFhagwqtz8IRhJFQR7W98sqdA=,tag:nfYPpIj+NmaB8RDFMR9bbA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y/QkCLGGjIqWfgNNQf1gFP7hbmAcdOzc8Ob+tROD/Q0Xb2wYcsXmbMlRkA==,iv:BFs4QuJfgn3gmiN1rdFwW5spCCrfQZTPNLe5M4Z9/7g=,tag:fQLwDMgTOeAxTOhlIiYBMw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:/1Y832t1piH5ug==,iv:0ihXpB9GBImc7QOAiGSAcLAchRSAyOgS01FU19W8XSI=,tag:vR9ofFER3CTDndGxwq9zCw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fbwsuAPt0EA+Igrh+tartVLqZVx4NZhm2I8aCMkV28U=,iv:7UOg1Fdmr880lH/JZUor0jF65w819oJcWvF+TVXfHbE=,tag:+2B4yluHfsgEUnXIKu1gkw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:4AHiplOgcKmcYj3LYZMNL5tBO+vFR/v3LtUvX1mt68psDQ==,iv:iQ98xA3lUlagkrdlpqB6xCcGq9or0ukEtzaa5OLG8UA=,tag:sxEzgdKZFlsk6v/HJoxxdw==,type:str]
    username: ENC[AES256_GCM,data:BDBRhGWrUyKGXw==,iv:sahA4laVyFaONhSlkjJ5uYe8gAleQak4msEAZvqO3ZU=,tag:FtK+e7aBigXY4HEaMKnhYg==,type:str]
    password: ENC[AES256_GCM,data:jDeNyIbAkgMJnI3dVgNU7l5JiMVNo9WAZ4029g4QlGY=,iv:wsansfVPSvcXpMidRXXvy/jOJgV4BTBLtdhpx8teQeY=,tag:xkNGXiUcr/OrrUZAA5O2fg==,type:str]
    #ENC[AES256_GCM,data:OWXocQ==,iv:dYwGUTruWvbYzGHFpQ49pif8AHqPieG2DIWJPgKPrZA=,tag:RoKohFvwBR4pqfOYpRVI+Q==,type:comment]
    POSTGRES_CONNECTION: ENC[AES256_GCM,data:62OCF88N4V03Ixr6Xe2yXNBAxekqhZSubuN3fyBEKoZ0Di7V+Qf0LXY1Upn+uEr7/TmLf28BP+SOHiaN7QwIrbOSQ2GhUvTmHjIIi6SRt37Jxiag/OIjwRfu5Hu26pdAVHr39qihLGw2C9hl5aRnkp6tTSIbvGHQGLSlvU1BxZ9Ow5ZMj4jT,iv:rTESX9YbAcE0t7ZY9+cnMHHMQkS0bpL8wJCvSGIi/qQ=,tag:OE6jTSEj5NuXf3JsyNiIvA==,type:str]
sops:
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWlB0K25hUkVBWlltUkV2
            bUIxbzNkT3RoVjFoVWI1WEVDdnA5SEVMUWljCjhtQUsxcjliZjJvd1ppcUxWRHFB
            T0l5ZEZLY2swSE1Ic2V4R0FqeW0zVE0KLS0tIGVrNVF1UTdsK3JtMDJsSUl2UHp3
            UzA4ZlRPMXdGRW1ZTVNLN0p5bkJCL0UKJBiT08FTZMuInpFjQLP0uy4E0Tgv2Zx0
            7WCU25EeqgtNd2nZ1vHRd5A3txWE/UE1BYqqBUQrxWrOECq5bzc+Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T17:06:51Z"
    mac: ENC[AES256_GCM,data:IEsLk2VCb1cgpck7mTS622lNKkJs72CgDNO/G6jApTd0Ig9aHGUvgy1V0UUYssvdBIZmrn5UIouxgjAsDgt1D69HIPwPF0mhdQ/kZkHv8bnNI+b95AjcTbcUmN4FhHWbVH55daV7OjirXN0zKEBm6nnnxZmJKTLRSu1qBDN6+uw=,iv:6Ne4eHtsaa1BktwOK68OD+9MAukJIBtAIECDwv2NToA=,tag:PxQCDFx4iLzKgklQD2ergg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
