---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radicale-test
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: tomsquest/docker-radicale
              tag: 3.1.8.3
              pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 5232
    # bump comment
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: &host "radicale-test.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: radicale-configmap-test
        globalMounts:
          - path: /config/config
            subPath: config.cfg
            readOnly: true
      data:
        enabled: true
        existingClaim: radicale-data-test
        globalMounts:
          - path: /data
      auth:
        enabled: true
        type: secret
        name: radicale-secret
        globalMounts:
          - path: /config/users
            subPath: USERS
    defaultPodOptions:
      annotations:
        configmap.reloader.stakater.com/reload: *app
        secret.reloader.stakater.com/reload: *app
