apiVersion: v1
kind: Secret
metadata:
    name: radicale-secret
    namespace: default
stringData:
    USERS: ENC[AES256_GCM,data:1qQ513NX96tMRxVG3swWGRE5ViKk,iv:m230b9Hf2wIlJDpuCUsRoNuUBOa/kbqrUtMcm6MZK7g=,tag:6JaARPUoDMA/nPTc0xFKeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q05WcklZSjQxazYvL0Yz
            N3Z0VXJBcVp0OWNLcjdoOFo4aGlsRlhwWjF3Cmd2aHFNamNCNGdkK1h4RTlGTFF4
            b0ZkajUvMkpocElRVmFNVkdrOCtOaVkKLS0tIHpFSml6S1o3ZDBvSFNzVnRlTXc5
            cmMzbDNrcTdnR2R1WjVRVSszdVRLU2MK1FMBPqfOJf4Fon30Lso2Blt1FNFVUjxN
            7mXK8v4POVZVIKcCpAD5TbkAbaNrYXajT361CsgG2EYiqhfZ0T9LIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T21:50:08Z"
    mac: ENC[AES256_GCM,data:OAYad6z553RcnAJyWvM8CjEuKPKhtKlZoqZdcTnEcrRuws3LxhliPI+BnCCO8FvPFYelh3XgeO2oFjtxDGT3uNKCMasTtC4n6FlYLYlZPYZ07mF3t704iKJZ4Kmm6ofIGsE7WqGjCZCVX/paLCZ446/pENYQ20XNPTpIyHPUfHM=,iv:hn4r2fQjiRRFhAAuCVXaYW0mJTReGn3SfbZ52AEHcQo=,tag:A4QNzpaaCYngmkfz1H1Aew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
