---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
    service:
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: 10.0.20.203
      externalTrafficPolicy: Cluster
    ingress:
      dashboard:
        enabled: true
        annotations:
          hajimari.io/appName: 'EMQX'
          hajimari.io/icon: simple-icons:eclipsemosquitto
        ingressClassName: internal
        path: /
        pathType: Prefix
        hosts:
          - &host1 emqx.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *host1
    extraVolumeMounts:
      - name: emqx-acl
        mountPath: /opt/emqx/etc/acl.conf
        subPath: acl.conf
    extraVolumes:
      - name: emqx-acl
        configMap:
          name: emqx-acl-config
    metrics:
      enabled: true
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["emqx"]
  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_password
