ansible_become_pass: ENC[AES256_GCM,data:DY4LSB+itasAZjI=,iv:5F6e9te8eRnN2zhcWVOawhRETwivbXVZD6oLKNjo0qQ=,tag:bmMvoKmoYTaP2sFy+EU+iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M3RuV1JEZHJ4UzJhUVND
            dkZUTkRNd1A5NGFuRlBnTEZVOFpIOVBCQ1ZjClg3WmI1cDluSDIwNERtbC85VG9O
            Nk1TOXNZK3U0VFdyRG5iMVM0Q1BzbTgKLS0tIEJBQndkdVRoYXZBNmVFcmVCZXFK
            Zm04SGNESyt6bVVzMVl2Z3QzbGdIWjQKDGIOS6SP88+cibQFReZauVGGgEfmdc9R
            N/gWGm7YLrfQGkJd4nME6bXcIdXN9MYZgkkdgCe5/Geo0DiCiAq5LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T20:25:14Z"
    mac: ENC[AES256_GCM,data:lSw6NyXhpkAujXOMVw73Y67ipS9ZQB9UHFNBESccgVUzRlCFX6cBc9Xe4jz6LV5xf0erS52wBB03lBlHBH/n3kxUEC/jYNT+aLoAa4TBZI1e6YZ2Rl1+hn/IKG2um9sGuNjZ6bsfm5v3BHWGAOs7jiKm782BaVBeMuR7jomwmZE=,iv:ID5QcvmotUBdo1Gc/jN+vBU0LWaib6L7CmJ/OW+dL78=,tag:4DQ1lbzP2Ohv/OIvTzwtXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
