ansible_become_pass: ENC[AES256_GCM,data:eB24ZdCHfFbRXt4=,iv:M+i6TmLksE9a8urAvhZItqCuI1G/LKaZ7dcVNVgtdgM=,tag:4tbqfLQoviT6ZgT1KnpouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL0c3a0R1RnVTcVdFWVB5
            aHlkRHhnOWZDckxPbWZMcjRxMkFIRTRWdzF3Cm1GM2Npb1JmTFF6MnlPcHVNRThn
            SG9qVHVXODlqeVNSVlVrSkNMN1JnMFEKLS0tIGRDL0ttbWRMb2U1MlpycDBONWdz
            Q1JROFFxZzZiMTFOa2NTSjd5cjZIUVkKAYMhUdGEQlVsq1GIQkHfyv6LVZfzobcP
            kmPw3nX6001w/226qfX9JLQpoUDQwKuhoQcP8PmCNZTkFlBRAm42Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T21:31:02Z"
    mac: ENC[AES256_GCM,data:y0Mk9Clug1JmBW0pcb7ljAZv2516gcXSpwcDrz6Ll590670K38IlpVgX/niDGeRslWtGNKG7F2Ye7Gxj17amNvLVxu/TN++XaHYS2j6CR1iUq0T9T5efSp6Fg++Lh08j0TSceU4EmFB2006okkPAHKlLlS6UeZPlZAQsG00ALkI=,iv:DXWCL5kZM72VUuK38iAetKYf56CFZKIGJ3hcDpL4SNk=,tag:4bqeE8N06vEE13htD6TmOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
