ansible_become_pass: ENC[AES256_GCM,data:zaqyiTr3PqoKJw4=,iv:pzoxu43awRu4tMGxRZdnwn8EXeUTvbm5NXHbIkU3mSs=,tag:aNPZqjlOAOIqFmsquBm6pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMERiWFBxd05jM2crUVJ6
            SjlMNGpGQTluRXRLZmdrR3hKcmJLRm9xOGcwCkl5U0J3MHBPUjNIZEtxSlBGSlZn
            WHhTQlhqL0NMbkFnd0pqQ0xRVDZXaVEKLS0tIHc1dnNWbjRJNWxOREtSOG5SVTJt
            RWJzZnZnSlJDMjV2bTVYaW9ZazMzNGsKaa/YmIg0OZgmW9vxBLVZMRZ9gqtEzYbc
            mwOn2HqVZOn6q1B8P1T3V/R1GI3O0wIXwxZaN3I2q2iywqSkFBSaCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T21:19:12Z"
    mac: ENC[AES256_GCM,data:Ls1nOoH2lYDE88H/F4/z8J4eTGyiUNfO8qswKyN226MYJ5NNp1GCKrxz8bCRdj7rvhb+vqqOZJRep98+Ypuy6JLsqR8Ns2vB/7AZTVRNfvKHrTtPeoayj/OIkkwdgsqP2Se0n9YzWpA8yKRwPH5OdgnuS1WqOU2zgsxnfTAczrQ=,iv:1ZF+tH7twd96gxn8cXGFX/0/zZKA+Cxs+tKP58gwpUE=,tag:9/XSL8DVKiAxnN5L5yU5XQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
