---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Jace Cluster
      darkTheme: lime
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - automation
          - default
          - flux-system
          - media
          - monitoring
          - storage
      globalBookmarks:
        - group: Github
          bookmarks:
            - name: Jace Cluster
              url: "https://github.com/ModestTG/jace-cluster"
              icon: simple-icons:github
            - name: Heliod Cluster
              url: "https://github.com/ModestTG/heliod-cluster"
              icon: simple-icons:github
            - name: Flux Cluster Template
              url: "https://github.com/onedr0p/flux-cluster-template"
              icon: simple-icons:github
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
