# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          searxng:
            image:
              repository: searxng/searxng
              tag: 2025.1.10-94a0b415e
            env:
              BASE_URL: https://search.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 3Gi
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: searxng
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/icon: simple-icons:searxng
        hosts:
          - host: search.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: configMap
        name: searxng-configmap
        advancedMounts:
          searxng:
            searxng:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
                readOnly: true
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
                readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          searxng:
            searxng:
              - path: /etc/searxng
              - path: /tmp
