---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0@sha256:d7eabae44168417a6acbc8f6e8510b0187a3f26d648941b3cf61b4c04a904da2
    env:
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.default,
        sabnzbd.default.svc,
        sabnzbd.default.svc.cluster,
        sabnzbd.default.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
    envFrom:
      - secretRef:
          name: sabnzbd-secret
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:download
        hosts:
          - host: &host sabnzbd.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
        tls:
          - hosts:
            - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/PlexPool
        mountPath: /media
