# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1@sha256:4188d3c29c53de1018edcfd5dc2d0a0c7955b9a239b91ff6c859626abd3494dc
              pullPolicy: IfNotPresent
            env:
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sabnzbd.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
    service:
      sabnzbd:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      sabnzbd:
        className: internal
        annotations:
          hajimari.io/icon: cbi:sabnzbd
        hosts:
          - host: &host sabnzbd.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
              service:
                identifier: sabnzbd
                port: http
        tls:
          - hosts:
            - *host
    persistence:
      config:
        existingClaim: sabnzbd-config
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/PlexPool
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 100
