apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-new
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
