apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:0xv12OKoi6ZcRKanMqd1P/DK4WI9y8B0Rvps++iN+So=,iv:vUpKJgDuCiv6FMhdKdhffXIge2omNb7H7yeNnvJ66CA=,tag:jYhEUFnNovoUt1/hER8sJg==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:K9gzw7rTxxpjH+9RLSiyLxSNbF7tjtVGWThTTndBMOQ=,iv:WThZxenofyj1VxsAFlQM0D2LvSlkj5t+xGFgYCvSogQ=,tag:rzVup3vjS51N4O0w4DClRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBendZR1lRSVZvcFN4TFMx
            dlluUDVFUUloYnhWcjNqRmxubkdQME1jSEZNCmppalAwUThpbVI3QUhaRExOMGFY
            alB5L202RjlabDBoSVBnV0U3eS9uZUkKLS0tIGNOUndjSVc2ZlY2Qkt0Mi9remVN
            UUMva2VPUWNFa2xBVFZOM2hTTSthV1EKliAn+wj+a8ACXS7fNfo6QbfDVVWVGGel
            kDxuEptlxpuwn54ypcjNMdo+qvxNLrd6bzygD3tan1KmhjdjSdNNmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-25T18:43:51Z"
    mac: ENC[AES256_GCM,data:0VKgg9F5c+qNB/6oIy1Bug4mkMaZfZ/+f5yktSGaI0OQR+0ARtANXw9D1Aqwdg4ghsvciQ6qQ2CV8qGVSJwqPWeXgcSHjXXljm6/rBXeSwd26o4a4+kcLnqcJOcVWbJwt2DGhemYtllRKi/4SAe+814oqfy+4IpzkaEP3UJwqas=,iv:jPgKTtyriphxlr4oJ3rQMS4r3EO84C9LJnWOrzU3Mu4=,tag:paZpjBZAf2qrpjXfx2tDRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
