---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-node-red
  namespace: flux-system
spec:
  path: ./kubernetes/apps/automation/node-red/app
  prune: true
  dependsOn:
    - name: storage-longhorn-recurring-jobs
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
