apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:T3qKcMySalbUTxY0prl11vjBzf+aO4KdCOHn0dTo85o=,iv:QUuOqo/PISb3i9dpGFj3ZLX/YkvV3FJV94gpTbePmak=,tag:8mrlWSk3VWjv0K0CSlyWzw==,type:str]
    admin-user: ENC[AES256_GCM,data:YWNI7DI=,iv:p+tVasHm/C6o8isU13QxOfQPgPRLu1jEpXPoFCSQSA0=,tag:xJmP1758Gu84QQ1uz/EI/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3pncXR2YUxCQ3lKZmZ0
            WTVVTE9HcVI0aXlRYWh5Q3dxMUtDbk5QUDJnCjREY2JmN3RiY29OQ2IxMFdpUGdk
            eDRFYVBBcTkrVk5BRE1yRXlkQy9NOTgKLS0tIEFtOFhOMUJSVnNUMDNOU05UcDlN
            Q0JENUIyajFJK250b0hGeXAxR1N0MjgKbirUJ4OJph88ERivxV3GQSvQlaPBQLYv
            eW0doT8kLZ1/Gm5aT0LKK3M5ArcTw94yBbppSbnzJX1w4s3YjR5mQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T20:29:38Z"
    mac: ENC[AES256_GCM,data:fNax96hnZUNCA3mI2/l1EMcMj9qMRGzzQag6/8tG0O9LVA9ygs6LLAy5/GyeLLJd0Deyzw9IYIUojs6N3xpOyM1SCAo9OlY+5vWNs9BhMF4gD77DVUdmEzXWElhWXwX2fJVxXX13kJ5ueh5UCskJEmzRgCS+jQWFSwh/sUlfdTs=,iv:C7ZqpYYS4yIUc3Ro5ITVmp9YiGwbAKa9kTOwAV3eTFw=,tag:FyDZi3pdAL1eHnKCj2l/Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
