---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apprise
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # https://hub.docker.com/r/caronc/apprise
      repository: docker.io/caronc/apprise
      tag: v0.9.4
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8000
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: apprise-data
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: bell-cog
        hosts:
          - host: &host "apprise.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
