---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apprise
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # https://hub.docker.com/r/caronc/apprise
              repository: docker.io/caronc/apprise
              tag: 1.1.0
            env:
              TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8000
    persistence:
      config:
        enabled: true
        existingClaim: apprise-data
        globalMounts:
          - path: /config

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: bell-cog
        hosts:
          - host: &host "apprise.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
