apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zI+rEehUTPCd816uUuuwiWe+VZs/nHHYsCYEU5IYUXY=,iv:rdNRZtZ01EdUCPmdEiAGghIVeYRFsWfWcTNekoGWK6Y=,tag:wuO6eP2bjCENjlgn/neqhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQUNuL2pzaTVBNVpuRDF3
            ME95aFBlRlJaMEpMOVVDTWJLdG9VTWpZU2pVClFaVzQwWDRxaFRXUU9qK09WcW0x
            c3lVcWNJNjZGb0lpNjlHcWM4WEVES28KLS0tIGgxSUlqOE9mbWdiSk4zVU52OUZr
            bFFNaVlpV2ZDV1h5MDJvUkpCc3R3VTQKuJSn5Xk6lu2/p2ysR2Vo6uPssAA1rmrV
            2KiK3flCkWF1DJAV2BcG2k6/SoUR74+BDqxme91DAbErWNwpelatLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T20:29:33Z"
    mac: ENC[AES256_GCM,data:XIO/kapDB5YzVpN2bTDsgrActV+cN3hkkX7lO9mdKyDR+VIUYvdFHXz4w7E6fFYuKoc5kEKP7ip6UY/kmJjygUL3W/T+Zveg0itRNNu6Z1rqrbpa1lfvy/Lds5ooCXF/ISkjVaF3eJTHPQpG16UTu3L4jQQqG9JuOaZIg4/hsZo=,iv:DLvmSmgskYFHIBHuOFL4YWM8pVW21V5I8LEuHIC2n7M=,tag:3aylvZi643wt/tOw9tl4Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
