---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: system-upgrade-controller
    meta.helm.sh/release-namespace: kube-system
secrets:
  - name: system-upgrade
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: system-upgrade
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: system-upgrade-controller
    meta.helm.sh/release-namespace: kube-system
    kubernetes.io/service-account.name: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  system-upgrade
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: system-upgrade-controller
    meta.helm.sh/release-namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: system-upgrade
    namespace: kube-system
