---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: games-minecraft-techopolis2
  namespace: flux-system
spec:
  path: ./kubernetes/apps/games/minecraft/techopolis2
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
