# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        containers:
          jellyfin:
            image:
              repository: jellyfin/jellyfin
              tag: 10.9.9@sha256:d6f3d4aa59438ce951d85669f3c22426d20edb7a6b97604c509b5f4825bc8294
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 20
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: false
    service:
      jellyfin:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      jellyfin:
        className: internal
        annotations:
          hajimari.io/icon: simple-icons:jellyfin
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: jellyfin
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: jellyfin-config-pvc
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/PlexPool
        globalMounts:
          - path: /media
      backups:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/backups/jellyfin
        globalMounts:
          - path: /backups
      transcode:
        type: emptyDir
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
