---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.10.1
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              AUDIOBOOKSHELF_UID: 1000
              AUDIOBOOKSHELF_GID: 1000
              CONFIG_PATH: /config
              METADATA_PATH: /config/metadata
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: "mdi:book-music"
        hosts:
          - host: &host audiobookshelf.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host
    persistence:
      config:
        enabled: true
        existingClaim: audiobookshelf-config
        globalMounts:
          - path: /config
      audiobooks:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/audiobookshelf/audiobooks
        globalMounts:
          - path: /audiobooks
      podcasts:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/audiobookshelf/podcasts
        globalMounts:
          - path: /podcasts
      backups:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/audiobookshelf/backups
        globalMounts:
          - path: /config/metadata/backups
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /.npm
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
