---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - pvc.yaml
  - pvc2.yaml
configMapGenerator:
  - name: recyclarr-configmap
    namespace: media
    files:
      - recyclarr.yml=./config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
