apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config-new
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: recyclarr-config
  storageClassName: longhorn
