---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-settings
  namespace: default
data:
  settings.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/srv"
    }
