---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app filebrowser
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/filebrowser
      tag: v2.24.2
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: &port 80
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:folder-play-outline
        hosts:
          - host: &host "cloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
      data:
        enabled: true
        type: nfs
        server: "${SECRET_NFS_SERVER}"
        path: /mnt/AuxPool/K8S-NFS/filebrowser
        mountPath: /srv
      filebrowser:
        enabled: true
        type: configMap
        name: filebrowser-configmap
        subPath: filebrowser.json
        mountPath: /.filebrowser.json
        readOnly: true
