---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app filebrowser
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/filebrowser
              tag: v2.27.0
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              FB_DATABASE: "/config/database.db"
              FB_PORT: &port 80
              FB_LOG: "stdout"
              FB_ROOT:  "/srv"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:folder-play-outline
        hosts:
          - host: &host "cloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
      data:
        enabled: true
        type: nfs
        server: "${SECRET_NFS_SERVER}"
        path: /mnt/AuxPool/K8S-NFS/filebrowser
        globalMounts:
          - path: /srv
      # filebrowser:
      #   enabled: true
      #   type: configMap
      #   name: filebrowser-settings
        # globalMounts:
        #   - path: /
        #     readOnly: true
