---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: default
configMapGenerator:
  - name: filebrowser-configmap
    namespace: default
    files:
      - ./config/filebrowser.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  # - pvc.yaml
  - helmrelease.yaml
