# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radicale
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          radicale:
            image:
              repository: tomsquest/docker-radicale
              tag: 3.5.7.0
              pullPolicy: IfNotPresent
    service:
      radicale:
        controller: main
        ports:
          http:
            port: 5232
    ingress:
      radicale:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/icon: mdi:calendar-export-outline
        hosts:
          - host: &host "radicale.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: radicale
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: configMap
        name: radicale-configmap
        globalMounts:
          - path: /config/config
            subPath: config.cfg
            readOnly: true
      data:
        existingClaim: radicale-data-new
        globalMounts:
          - path: /data
      auth:
        type: secret
        name: radicale-secret
        globalMounts:
          - path: /config/users
            subPath: USERS
    defaultPodOptions:
      annotations:
        configmap.reloader.stakater.com/reload: *app
        secret.reloader.stakater.com/reload: *app
