---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: default
configMapGenerator:
  - name: radicale-configmap
    namespace: default
    files:
      - config/config.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  - secret.sops.yaml
  # - pvc.yaml
  - helmrelease.yaml
