---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: default
  labels:
    app.kubernetes.io/name: &app radicale
    app.kubernetes.io/instance: *app
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-apps
