---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      stirling-pdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.45.6@sha256:fc53d48a018cc36446a4b1373db633be51301b828755e312c386b7700cdf2318
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              DOCKER_ENABLE_SECURITY: false
              SECURITY_ENABLE_LOGIN: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 5Gi
    service:
      app:
        controller: stirling-pdf
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/icon: codicon:file-pdf
        hosts:
          - host: "pdf.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      configs:
        type: emptyDir
      logs:
        type: emptyDir
      tessdata:
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
