apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-new
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
