apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-new
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: sonarr-config
  storageClassName: longhorn
