---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.4.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
      addPrometheusAnnotations: true
    server:
      replicas: 2
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17.4.0@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
          envFrom:
            - secretRef:
                name: *secret
      metrics:
        enabled: true
        prometheus:
          serviceMonitor:
            enabled: true
            namespace: security
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:authentik
        hosts:
          - &host sso.${SECRET_DOMAIN}
        tls:
          - hosts:
            - *host
    worker:
      replicas: 2
