---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-authentik-scheduled-backup
  namespace: database
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: pg-authentik
