apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: security
stringData:
    #ENC[AES256_GCM,data:ORLP1ZFSZZvteA==,iv:cO+m8J+JvewWETu6sCdlWGNHl5zSrhwn2L7mq+zNKCE=,tag:1Ip3BMxd/9Ykha4x+Wh8WA==,type:comment]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:DezCwiTTnqig+vMloIIDwGFmxUaDnIk=,iv:o1rV+RiFr0mvkFEBjKpf3CUMiA4hzxm2pb6T/jecGqE=,tag:oSooy0qAlhNJ8sg5PJ4Vsw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:IFMzhJx1G8s3g3xNanGBSXgBslRckRLWCnKD3HRpvIk=,iv:2pCRxGIpVqjrQehKkTJ0/XJU3KGgg4BgYIi6nxxQknM=,tag:9a9D2tDDt2OKG2bHE59w7Q==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:bfG6yP/pvUBD1t4fc82crQ==,iv:nrGeC3W2gEE8YwbX/VOr0c3SUSkKFrwd7McVh7unkak=,tag:zsxR6XlWG7rCl9nvnL37hQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:APsRRGrqDvNF2zXDKboAJNTM0Ut4BgkB1indeuSCJ5AwEJbtYXj2ATXFNC2tjBacSadXI16jMfJQh+5Uz7zbDA==,iv:VLOS3SA3NrvdW90Z1gR5ZGb7KGpeoiynOmQuuQa69Xw=,tag:L7yeTLawNOhgLcOK2H8ATg==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:3A==,iv:r97xDTdL5Beap5IA/ApeMYjHXxrTSaMXo+U7UCOK/tQ=,tag:EvxjS6ap/IxBSIcL/mfi9g==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:IkvYlAVeKJ+ckbPer40AwDCCYCWWTOKBd1nPYcOyt+YhGxrC,iv:UXdDOkI2vCx+vvkjIFPX0lDJ1pgl5dPbRqGqjlaoFHE=,tag:7cZXbrQc8ED7TtYKv4G9mw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:zcHf/tGl8gKd,iv:VNVu7H624auL1c2QBA0eUECouDmklm6pdUa2T+i2/U8=,tag:RX34t21kFD6pAeTxdteqDA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:vq6y995kKY1mcGCeMRPZdaByjTi/dWMeW7MZUQVNjzRfDs0GXKuljIeu,iv:+/sfxvORFwSjhz9+blaPIA/10rgnLQvC6lb62UTEyMQ=,tag:1NFZ8vNikBTKwCtBB2e9+Q==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:lJSACFNrcNtp,iv:ngsuPeQwH0Pu2UX7yzpnqnFy+9fn/zE3CLv/LXMdk0o=,tag:lz7sgzMZG+3VjLFStztYRQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:KU+F0lV3hcmuP7cVRmMKLxVVRdWwhuudykWCJKcBFIk=,iv:xe4KNIvPQuWtyRcxYWnI6/gWWS7VOdhr4Aq4Gcf2Omw=,tag:F5uzZkkPr3Zi2cTHjdn6Ag==,type:str]
    AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: ENC[AES256_GCM,data:ncWtTg0=,iv:79rGxNl5oyWee4+McSyjNafCXI7hpNSuXRAhpj6xJmk=,tag:dmGyqXnDvP0xFF2GzXkXSA==,type:str]
    AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:sMl+9pQyEA==,iv:PsZ5ki543AlsjXWa65xqQPH4OI8tPqw8nplBWmH5Lc4=,tag:hTqXw+tU6druPV5Qvhz2AQ==,type:str]
    #ENC[AES256_GCM,data:K7P4UQ==,iv:aaWMcNbJkyvTSUI7YGV3PLBYaKUVK3F4eSGneEjTj14=,tag:OD4aZlGlavj956eGpGQc4A==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ytVAlcQiDJL6,iv:qDtrEcaSR6rCS91NQt3bUiksA4pskWzbNH865my7TJY=,tag:Ua97dQwW+jDgpKVTD2rdnw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ABmmvYQJkude87DgyD1HVbs6QNE1jiq05wRSTzfuoOsRPOClJVHsCDXO,iv:G9qm/hPs4A1KUAIQ9Q5VM0Wli/jOV3HKExBvx4RXmgg=,tag:SGDjMePufIxZpKamF+O7Aw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bMrvQGq2U5+h,iv:5V5K5/JUb1XsHkFNboJqIVtnHkx8nwy+CwU3CRRyNTw=,tag:TDdJIcKsVzXov6NXbacafw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LytyJfQ20eZw8WM0MovQcQ5WkZhlZ0HctgDhdI7mN9M=,iv:OwjVt0gV8F6IBkUGfC+9/4ep3MNtB0EIUohJ2xQjWII=,tag:X3/UbXNezhmDXbex/YOp5w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:31NX8bhcNuMdKbSv3pCUsH5SebCRpgvYuseeTcsAqUpE5g==,iv:5t0NRzI71UrpuL0KPQLBSYFbS2z4ker4Scm4NOgTXyU=,tag:eqy3Xdr4N9/mEoyEDgIJaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVjVaNEpuTnFtUWlONnhM
            UEtBU2FZdCtsTUxFSjkwZTJHdWhna1dYV1F3CkRQZ0lVRDRsRm1WRWlzN1cvQXFZ
            YjVYUTNaVlFaRnVLZktQbnQ5Q0xDQ00KLS0tIGRYdFAxQ1dSNE9jSFJpSVdYSmkw
            U01zUEVmekl2RnRVNHFqVnZ1VDNJcm8KFWtCVaCJNYT+uznAz+a075/HOSCWBT5I
            GAOaZt7deKHzG5MVTrsxzuvICe48VJKPvyrXWf08xOopwKjjtSNGsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T17:36:22Z"
    mac: ENC[AES256_GCM,data:PEDCaUmfqv9vE+tnx2DnYW3fXJQr/LcT/H32kP5xYsySmdNtw0/7TPNy7kGeo6kJoz8FeHZVgA1KYj0CDy6/QD0ZiNom6ZV1DI7f336X6cpS6lqozGzXwDg0fYtAfjBv2BfNPsR6Zfn2/vuxL3UpELfLko5xmFNgfB+r7ipmCZg=,iv:pqCyfY3+ARar5Gmbbvggt++SpOQpQbCAQB+msppaPhU=,tag:PdGUDuZmyWyYK2vOJuWuIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
