---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: games-factorio-saftb6
  namespace: flux-system
spec:
  dependsOn:
    - name: storage-longhorn-recurring-jobs
  path: ./kubernetes/apps/games/factorio-saftb6/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
