apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:RJERgvj3zLYASWEW8sfJEp7juU2OrMrp3Kn77wCFBbogFdBOXwBjGw==,iv:EQwtYSrKm6Qihio90i1QWHG1n6Us8iit+L9IX1sIauw=,tag:qd3u3GEtUSYbueIYdDoGvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RXlRZ1NFM0RoNVdHNXNk
            TGtXL2VudjUzeExtMjlTeVdyUTZVZjdzcjE4Cms0NmF3TllxVTR1bzU0VEFid0dV
            cFlaaEpGOEdRZitsb20wN3dOaU1xODAKLS0tIHlGamN0c2lmK2o2TWN2NmRiRGNQ
            R25MM3NlZ2pZT1orVnVlU1FHZENnbWsKIz678zXPR3+pmDqlZhzrIyvMCkMQb3hV
            X+12Jdbi0IAXidiJUiQE9e7M2xUBJWgX1k4GGaUDadotsr292KO0Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T21:31:51Z"
    mac: ENC[AES256_GCM,data:C+E0w/rC1pYDAejwVxKEspv8e9jyhU72qXH/uPrm9wIx1GGD/VE7Q0yLhB0cykRnYONctpMIJ1bmFMqJ1rZKnmP9f7HHythxVcrQfIFpUwkeDmVeA/ItZx64GZ28wc+I6EutgZL8XtY8DU/jp4fI7eIbdSWmuoYpG7CbpmpDjkk=,iv:yTQ6ynymTjFaxSMqn9k9p/Dlac8pxf1v8KdUoQiILCs=,tag:s6BOgZmp3cEoiJoxUZvQNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
