apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
stringData:
    #ENC[AES256_GCM,data:QyJcrlp90Q==,iv:NccIn94VwNGDuJM531HmvfchXNXymVBYLka4Eyz6A+8=,tag:uqR8yR4I8T4b52nhXNuGjQ==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:AagpLsz9,iv:xW+rcZsfIS+LSKvYUDCzF/0vzFMTgQFcW8JzQOK3tvU=,tag:ErPJ1CjjNU38+ifuIxlYuA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:1EOvWA69VtgEA3VkSl5Ec0NvOv507GA0inuLf80C7FWP4DfC2lM=,iv:ftP9O8ilkuPImwJNc0RwhuKyEdhH6pPzJWexqR8Gn08=,tag:mKGe3MjEGBfWmX42MTY0+Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:plRmmwGowzPSGJRG1liM4yLD5D0D/htaHMUWqva5pq4=,iv:2ayi7KQp21aQc13KOzTDRRMbvt4vIfNiUO8mcLPBCh0=,tag:noLWUXdIXljDRf2dI+Ddkg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:thaHCiON,iv:Pbw7g9KuTm55aUxmdXO9rWcs0pdQX/W3+rYNEygF1W0=,tag:LQeBx2v2D1GwxIP26Jzfng==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:M0GRW9HjdR5tOPlUNYxoMfZuIqZz77Q5wnS/RbwuG7uH4GmMAAtauDpJQGKOa8RaQVs296S3EXY473zYNDKVTQ==,iv:RFc6feDiNewDuTj9b6Lab76qPR+YggBnka/JKdxNIy4=,tag:Os2BrWnL1Zqd/bL2DbRaZg==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:k56QXiE/7xx99Fmj1wPVGMh2NczUc5BC0NaXrTsMA2Cr5V/Hg/PyCv8Ph4zAyZSf4hIuHgTFuUb9zAhHhIuuoA==,iv:dVJLy3N2CXg+CxkDWyWl+S01hVAJla6OeXR5guq8pO8=,tag:M/su8bZ0FczQlB36Dehb9A==,type:str]
    #ENC[AES256_GCM,data:KSVL+/MqDolumtvXv7M=,iv:5mGmlKRE90Ybv9TMlSSV2tCq1QZdoKPaaV7fyNUCSg4=,tag:lZAQJbR+N2ej0RL/zVLiNw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:OOLiBLrS,iv:96y4IQBZl6yBdpQ+1h37yX6Q513YAa1yk2aZzBNJakc=,tag:Mmm8mkTUoO5C9bK+YvJKng==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:njv15UJQcHovf8/Cebztnqki5SWuUROc17ynsVEn/toJF0Ek3fQ=,iv:+meCtxp6CcdAUtEVV3ZADyFl7PXtZKhV48N83AJgYgw=,tag:D1oJTc28lAKz0kQlmgIthg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:l6NfRnXEv+gOuKB8uokU4Ocun1mEaYIPC4gYJGIA4sk=,iv:DxEDWuuFB5Mo1c7KLD9l+h/QcrA+1yAuAV9uWx0E6rY=,tag:Omp0k4sE+qQmaFfgOYILHg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:AadVk8HVIzQ6MbR7M4eQnTmSfXKcvx6iGw+niq0d/ARJvA==,iv:mOlrsmJmu8O5bEEocfpnvKdM0x4f3aWvvUsoLgkKjyU=,tag:3vzCKbgMhIR2jwVTYtBS7g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:LJaXXkQG,iv:wNYJJSJ2C/emXVZ9y4/1v0Hg6N8p482heC0jXAQ9Euk=,tag:JxxDZ7WmoqPJ+r1UCPA3Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMWNvZnk0ZjFIL1YrVTJh
            cGdiN3VlVmx3QStYbFdqSEJHelFsVTBBMTBVCitwRUhsTld1YXVzdUwycWlQQXkx
            U3hZOVd6ZUtONDNRMkp6M25CRlhwa0EKLS0tIDdTNlhZL0s2RWJnMCs4ODVjVm84
            bmpXWFJ4b3d4ZG1QUm9UL1ByTXpQRUEKPBNYf/J74HkLnQGfiVdyQu1jmNhTwRlW
            16d/2B8Ze/2qiZwV8+hmeBlHb2G0abSm5qt+u2rjjwMs/NMTxgQ7rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T21:15:23Z"
    mac: ENC[AES256_GCM,data:TbwB9abd4fr4ePhc61VqztglL3XvPzVtDSYn8k9GdM2oncRu1/Bp6/aVefWClDrEdhzwHhifP6TCIB59E/M3p9x6xwimnvcRCQ9WOItiJ4yMawhTPSx/pH6vu5YXFCur+soAxMwSNcQ7WUNgY4OPj8PYFGB6K4k/vqraKkGZ9Po=,iv:ul32hBPxKhkc1E3pqgYOU7V5/8NIkQP6el0kL0wSnxs=,tag:0EbNAHrzz//SBuc/XBg3zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
