apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
stringData:
    #ENC[AES256_GCM,data:pbkEJPNTMg==,iv:+qsIQclMvfzG9IYoGndI7Dg2sI3NDeX9wAOKuxwVk3w=,tag:s/hUXPI0teWO49yYPAZ5Bg==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:2sybwCig,iv:nHVdyOU/qvHobCEUB3m0iFipLM39ijZliG5wEaE/Reg=,tag:RbeacSNugo0q1IVyv8usSg==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:9vfKqVcDvPbtU55QJv9SHbK7w++MiJ7tRTnl5cQB1GynWBNVeg==,iv:DILD3YQfn5PHrm1SeZU/vWzIKLJtNoda0LSPQGuHAho=,tag:5K90ttoY9boEzW4yqK//nA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:LZGnZNlkG2AzB6ywtr69KXdvi/u2d5lxOzc1uI9Psxs=,iv:91+1W1aqiekJr3WAVWOt+y6Fi3qKPBLHTfGo0smQ5rs=,tag:4zxQQkAZzI4et2tHiP6XZg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:xlZfrc6E,iv:05mc+XisCsLvLw/rAlh9S5548iofKeMQg3ZmNlHKq44=,tag:sLX4rHidLAR9+1t/tDgA/A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:MiVYdn2F6Xk9T8GBY9MBDaynOeWDtIDaEqG2VTY5NN4UXG+AAlXmSplOTyNV4AuR17XNx9R/JRaqvHPNjVnkDg==,iv:Bq6VSzCBhSWA7qdHcYaRa6WAEL+UiYeRj70INYNx+7Q=,tag:J1oXgnRMaaFEwUDNN0NkCw==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:zzCXB40zmeuB8OoV9jbgHud3u58oL4kwADDuJFrBkGjb3p2RuUgX5LvHBIXQMIx+WzfDvsJ450wYidKPBByXAw==,iv:zQrzYdwWoIKpphFWYHsMSIo6pdMdmJuadMphk+qitgY=,tag:3+0lRo6ilnd9Yj/cZqAhcA==,type:str]
    #ENC[AES256_GCM,data:gXaNC6LZbn0hSB9nSHg=,iv:9oEWa+Q4xNvBs2m1A5LWK/UdPFuSQL6kUhXl/s/DXGg=,tag:GTdRuN5lYNoa+GbJgXkUyg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bEynmy21,iv:45okGw79qBwI231RyXRcMQatN6/13aUX0cTcr3rNm00=,tag:mx2blJ4uYQXT4fAQtHBpUQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:F6+euLSHd4F637qPMK145yPx4a+H0iDlQGUG5EcEZ7C7g3AeAw==,iv:vJpqRcKsS7QyFJlncsP+92Lb0r0E2BgNgx0W/NUjBtI=,tag:mTh06T1ZMbdWhg5rvXQ/fA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:oj2BC1/JJIAc1u2U07rM99pkRcItYm+1z+G9yea89qc=,iv:/p93mqDcewHFcuCacFISjjoJHvSNb+fe/SRQkMIpPnE=,tag:TfpTTzR2Uwhd+Jl51dA4sQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:QIUvgNnDtolS/h7RqgouWBbXGByvqj7ed6rq1ZMhhFL/fQ==,iv:WZ+Z4TVl+ldPZ71469XOF2XfgXl7Roi6jveV6C1K9z8=,tag:5rwfClo60iQT8lkP597NAA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:r0GZO9xh,iv:xH9xYvHT54Nxuzj/eXaXk1etVdJwy3e6rz8aUcfMrX4=,tag:RdQM4CVXST/y7QLF2eC9EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR0ZXOVcyRk01L0VtK2ds
            b2JmR29QaGhSNDIyL0RZUktnYXhPSVUvYWdVCmk0NEM1ampCcXhLMWtxZWFsbXI5
            TEVwaG13dzhRTnlhM1N0V1ZiVzhiSkEKLS0tIElMY1pvL1JTSkhMZ0NQV1hsVmxY
            MXZGZSszaWM3cjM0TUJrWURZWDhUb1kKHyd/RgLdbD9HPxlusWr8GB2AZWTGvD1n
            O327MMDd7JeUejFzglo/Gsgt77ySPU+JZMqgObYF7up4yV5FCsuVDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T22:38:18Z"
    mac: ENC[AES256_GCM,data:usVqOmd1D0LKMSbbCpPTiAxcatrzIahAAJJJfMiOwNLGn+ar96ODVthdDeayww7aahl2knqc0hFxJBtypCZ069hNck4Z1dvYCAkpwiEAGl2NdqqRsV/5lviYcrpmQbr5JBmzXnSrbgyH3lcjjpVjBKjCR3/pIYMW+ApS6PEB6pA=,iv:KRFnRsTiDVcPh8XNmPFa40cJ0MD+2LlJINrXI+IMLPo=,tag:SJRzUWwnkTCFdXyxBdkj5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
