apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
stringData:
    #ENC[AES256_GCM,data:14DivfINGg==,iv:/NRNwb55PUZQTf7E5IX6i1EG7YjVFY9A/si8fp8LG7s=,tag:brklZnD5SYBLczk0bjh38g==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:08D7pjYQJA==,iv:5yM9kMxAZs6YCU3cL/p57TWYqZxqZpjKt91r8jnANGw=,tag:czcSs3tFap6FxkSi2GQ7rA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:R3smnrtFg4PrEvy4jaSwFCsa622jc/HmDAlWPqRVyFl2zwnbZg==,iv:zYiAH4up63iPaXhNoP+ny1LkDhMiB752JaMkK4sGFTs=,tag:CDricib8Bz8B63M6x6LXBA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Tn4oPlrPzU1PdHAzADiAPS2f/R0dRaf4RaluL2WN7yU=,iv:YNS6SOXxY6Y19L+zUvOH7COyxOgN7Xdo9/O2AjjNydM=,tag:v3khHyUYVRKVdybioDwsmQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:pcbehGZN,iv:bcxACxLwHnqnoIdg8H0NUhhNCzgqMtXE9hg96/ZFonM=,tag:/flEqmOky28wkseDXw/B0Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+hPKND49EfCAYH2hbHdgsd/XnWq+ComgVSZytKI6hG+d+iG51BaeZUiynZM8/zN5JiTvtfXahLdMJ1xhUfYPxw==,iv:qCYE51zw3W3ejHrZwU0a3FRGgvmSP5qbQyQyMHG+aPc=,tag:+/VJ+6vKwWxDBKAuVJHC6g==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:TXeq+TsoMxw7RzzoEZMLNXNuw3yrlVBj1RKAQBguPOwoswiE4zCc+qzxKc/FMwdvojZ5+t7AfrqlxlO68Ks1eQ==,iv:EPOWG8YPFOVrAPtn+46fpe0CiOJ3Adwo0Nc5U5ACsms=,tag:I/YSzZ680egzS7LR981x1g==,type:str]
    #ENC[AES256_GCM,data:sV33/RnxYl66SbBFaOM=,iv:E2q4McLI4KXhYTnGiYrvNhxDvevSngFpWttQA5Mg+yg=,tag:/SsAGtxh1EFpF8o9JGkduQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hYddcOge2A==,iv:I1qYgkjOIAayBkwwTxu9cM9WOUEIKcvFwPgsrNafE7E=,tag:4zM7S4xh67XZFUjqYnj+KA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:rXnwSGThgz3kGr/UqKyQ0FdH7kdFAGzB3wGjq/aznRv/Y9mmIg==,iv:Tb6njRVw0UPrLKgdCClcW0rENJuLA+n2AcwWFyExhVo=,tag:AQ70cAulW9x+ZdhYSqu4kQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Rsm6ozh/o7CPS1+cbqvqzEw2WY4r2iAQdkba7CAOmio=,iv:I//knAYwnv/+0XcIpwMBTGWpWNCXvkY09oVcQpfc/NU=,tag:5SyUq7SbXSE4OmNKDB/jTA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OkR0W4r0aljW7+pnLHuV+z4Jwh9GI51DoafU7FaohIrovg==,iv:A1X8RjLuLtgyY3XTGny39e6nD18mCrbLerhjL7bnyWY=,tag:+PPEbf4YcPKoJ0GhzscrAQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:O2ZzY6uV,iv:nTwvPFrO/R7Z5D52iH5mIT+FDh8Pih1GTT+tQgIKw1c=,tag:8YuYHDNZBmI3dpp5OWndYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSGJRTm4wK3NZMnV4cE1S
            eWI2SHA3YTNEaGxiMGhlcWx6VUVSTVhZSmk0CkpNT1Y2UG02Y3VJSDBBMC9MUkNV
            VExtclVXVXgrME0rMi9FejhRVmlHMzQKLS0tIExCaTBxSVJCMXNibXZKZTJvUHly
            UXgxbW4xQ1BXMVRndzE5NkszT1dVbFkK2kKVq+Qd6cMUyNAzNSDrZVg76BJ6e6U4
            YySGiR2tawr9/rnX20+Nz/OjIz/TRrdWAdX655z2d2V89/VCI6R/Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T22:23:51Z"
    mac: ENC[AES256_GCM,data:WomF7CeHEbSSir8oEWj2COkBfODILI3O1EDdUO5Gjc88GtwNhCB/xQJOvhswY75SaSPyuihK9INw7Zbz/U73iMr1+pu3MuflHIJROIu8iALm6b3igdSdX87CBM110voLLr/wslNOQeBfUjvts/9HD0nK6AeGXit49MvbxS6CPkU=,iv:RA+qnCEcjE0irLep9FqLcIyXy/s3hDiU62EERkj4dtg=,tag:zJ8y+Ovn5RDf7aI5sdluKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
