# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      readarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          readarr:
            image:
              repository: ghcr.io/joryirving/readarr-develop
              tag: 0.3.26.2526@sha256:2f17ccb13c22596371a83684493e46cdd932889581277a76e0591a1d341c152e
            env:
              TZ: ${TIMEZONE}
              READARR__INSTANCE_NAME: Readarr
              READARR__PORT: &port 80
              READARR__LOG_LEVEL: info
            envFrom:
            - secretRef:
                name: readarr-secret
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
        - host: "readarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: readarr
              port: http
    persistence:
      config:
        existingClaim: readarr-config
      tmp:
        type: emptyDir
      data:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/PlexPool
        globalMounts:
        - path: /media
