apiVersion: v1
kind: Secret
metadata:
    name: readarr-secret
    namespace: media
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:z49+J64tu45RgUCli1Qj01GIW2FZxR9Xq1k6JIL6ejKnO8j37jKflLQ=,iv:V8SmuuDzRM0HoO+u86MXW7qx7AyGVkzenCSFMUbb9cY=,tag:WeaK18djPNARpb4NYdXF7w==,type:str]
    READARR__POSTGRES_HOST: ENC[AES256_GCM,data:KPPXJqmJ3a3ydA8ZRUTVayISLsgvjiCSQ2aQwMfboSVPCNC40bs=,iv:9OT20X3JCe4iZogCbZoE23Vb3WylQ7AWFPryL7XS2wg=,tag:Q6C/Evxi35qWjAcCh0sp9Q==,type:str]
    READARR__POSTGRES_USER: ENC[AES256_GCM,data:PqSMrq2nVg==,iv:fJ5UpexqFeH2Z1JhO2ZHi8+OOGcPHUinMsmfkjdNhgE=,tag:ui8cxAYCKDqsrYT61LcYhQ==,type:str]
    READARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cav2bVXWkn5jSYT1LhKNyGoMZHAFZqUEiml6xRyDjxk=,iv:WFrVUad2rRHUmVkULAEd/n5oJSQtktacwwkVSkv6xbc=,tag:yNtHhei/+QZZr8rvDxJ36w==,type:str]
    READARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:mXYXdxbkrXQEJJBV,iv:nvKE4D6ZIPIRN/hrw7tTo8gLSTfa8ikad1f1h/pyAhE=,tag:C7KYZSy+MNARrBE2riT0gg==,type:str]
    READARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:ZJ6d3jqmWmF+S2U=,iv:eQazXtWR/tCoKWEgJrp1VryeSGoQc4M0E1d4ZmVekuo=,tag:QV7C5CeCQUdTW+AktqGCoQ==,type:str]
    READARR__POSTGRES_CACHE_DB: ENC[AES256_GCM,data:xlJlAlGJ+ewb8YmalA==,iv:6nBtGORrOiOxhDfcJXcIZqJcsP0+skP3n5WwYYOOPaA=,tag:jHCzmWIUuq99y4Q2P7i3Kg==,type:str]
    #ENC[AES256_GCM,data:O0IrrQVYYG/EaTkPbX8=,iv:XEmZHbI9qyoNHRFXCOHrXr1MXJ21CX1JFM6SzpgHL6Y=,tag:H0Fuld2RyWPrX27cCmAbvQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cmd1aXiEZK0VUwzjnnoI2zjICbnMov2yWqIt85g3pVKkG7GpmHU=,iv:6wBWd767+3cBqhelWICaqJUO0icO62CT4gRKKpJSOrw=,tag:s+howyuzqIoM3HAvqFE++g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:XnOgPFGnJ3qjJMzC9jRcBDFyilqOY+8bBapCT084mkMlUuaHc+c=,iv:5GygcwzlrE6j8xN4bom6zexbYgev+uLpGmyOBJORJBI=,tag:aNTmmL4lYY10jDZ0MlgNfQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:K2C7Cq/IhQ==,iv:b+Kx4ovvsI1Vs1JZnmnacDSxLpsUhriU1/oizHs/gqk=,tag:9OeqItZw44wHsWMCPaJyMw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:tabbro/Ib46y51RXzyYGppkH94o+Xyq2Sej4mIp5SnA=,iv:KT66F60qNJGDosLZ2TDNMTeI0NnPOjdgQbelyOW653I=,tag:JA2HSb6HJJok6icJGoidlw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:PTqxklK4qbuAzvWN3COY/BT9/YSgVK0mYicMId3AjT1WnQ==,iv:YOsU7dxaOGueCW01pr3Jh/ftfGUk2nj8BNYyZAzbtec=,tag:+FXq/ZN/we+Sub8B460sqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MHg3OTVTTmdaT3JOaTAv
            Ym9rRlhreU9vOHdtaC9QeVlHVUNSV1czVms4CjlhL1E2Wlc5N1RmRXZVSmpmL1J6
            VzFTTzhVdXUrMktFVGRsNmxlVStkNzQKLS0tIDBpdG9VbkFHWWVvTXBJMm5GQ2dO
            MGZHaWExMXdJMi9qeUE5S0hWVm9wRkUKjbr5NC7Rw0n55fBR0R8rrRi07xOhA4wR
            NZgA18XRE/w+98BaJ2lO5gxj0f6drHLzl43fqUxgRXXEGnC2rWVelA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-03T16:49:11Z"
    mac: ENC[AES256_GCM,data:9d/4zcox47ncedlAYdneCoZwY86n1iTPMY8KEDR3HuyhNAf/2S8+pMMi34d6t9QJDkW/r7jv8qa1bq3nZBvisWC1O6/Gt+97S7M6Azzj1yNA9WVPKDJs3UsEx02QV9s4aErzEOrXe8FB86qZq9swcyOiLBVbUAHTNdTBI7J0TwA=,iv:cq2GQ6d4aR29e0n5Ua66bE7PnJ31foNipEiIQouFP4Y=,tag:VLFbXrPyYjGRgWHSaIcaig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
