---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-prowlarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: database-cloudnative-pg
  interval: 30m
  retryInterval: 1m
  timeout: 3m
