---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn-apps
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2023.12.4@sha256:fbf40169fd70409280bfce460be144a2f49e1bb9f3350e3f775e308bd3379885
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              POSTGRES_HOST: postgres-rw.database.svc.cluster.local
              POSTGRES_DB: home_assistant
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.20.0
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - "/config"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: 8123
      codeserver:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host
      codeserver:
        controller: main
        enabled: true
        className: internal
        annotations:
          hajimari.io/appName: "Hass Config"
          hajimari.io/icon: cib:visual-studio-code
        hosts:
          - host: &host "hass-code.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: codeserver
                  port: http
        tls:
          - hosts:
              - *host
    defaultPodOptions:
      podSecurityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
