apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: automation
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Q6xWQ2Q3xydoY9scyCU=,iv:2bq5nzSVMQmbY1oV9yOBJ0LtVa1cH4MPM9quX4kePIs=,tag:ABc5V9qwP9as5vNgMpCVgA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QyzEy9/2mbYCIDn3bg8vkTx9CVmBiHmOgIg3kj/Oorsbggts1iE=,iv:eydeTZKXzTAuyOkMrzmL0IqKuXjTX3MFn5ZyOggbfF8=,tag:J7X/5ipKX/ZUuDYyc360sw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UWkHIFlQCBA1ywiJoQ==,iv:gg9a1z09dmEjFgZXR6jXEkdBSUPMieNUmTXzmNHEibA=,tag:rA5cFbWVKJTY+ay/at1iLQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ir0G3hlBmOujvZsUthf+6LXWBeholBGSRbJdfmyGWDk=,iv:Q4vmCwD5N8YmTUExRf15IIR0PAW3hhyew3Doi89waUU=,tag:O7FWBsvdAfDnuqqcb3tYRA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8WghWGVwj876UCJBgKgFwOklp6tF6glGQzmmUJIPel8=,iv:HDH6PUDmHJRHKreTuPOBo0whi0dpZr3ngfwRbsvkpxw=,tag:Bx1jc1SwG6SFo0nGcqEriA==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:O8Hg4w==,iv:hDI4nveuOBTTxwLzkSjLOswYTxX0vcH4EN9G7Ai5Ro8=,tag:+ZPTACsx84QruXBHHL7Znw==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:Qu7iackKtFw=,iv:uYRo0x4I1I9OlZZ0B+Owx5V4gKc1tkvsfwy9oZSgKuM=,tag:YLoX9vPVVOnjfvkqWufTqA==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:YIkeAjKheB0sXQ==,iv:DLn8E/gFQ2MyxNTzGddLhSajUBvXFTuD3syF70vZ3cI=,tag:S0F6Lp208Kw10TSlvp0MXQ==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:ugVWwpROCLOjlyElBuB3nVjh6UJQ8Z2tk6FgSTpn2oaEHpFDDvg8pUwaE9e3ARqgnd6HYqqVSOoikch6fEw7Hn16pWjs07D6QqGf3pC07iAZQnx812nYcaw6EGyYBTOkE5+uEe5ULmAfTartC+QdGbs=,iv:rUrmAixSpqgYaIKmGn2BxPZQrmOGwFAtWiVsD7TzP9M=,tag:BAMII76B7FtvtV0QanuI3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaamNGejYrR0V6aGcvVDRm
            c2p3QkhRVEtyR1VnTVFJMGtkN3ZKK1psNUdnCm1jZVlNZjR4SG1hRnlLZG5Zd3Z0
            ZWN4TUtDVjg3M0F5NU9UUHRKYVQ1UjgKLS0tIGladmlnazcyenZ4Q3JFb3V4dGpB
            NXVTamQ2V3NwN0RnSkRMTi93Y2JrK0EKudJRRxK87H9CP63lKlKrod0yi4OLbtaw
            qRPhzla4wdW7nMqHGPIZCz18de3M75O/LQO7bOxWjmlOXsYhdXvovA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T00:25:11Z"
    mac: ENC[AES256_GCM,data:YuAn2BRfPcHBcAs3Zby2EQwhBkLSWrOB9CUyaUtpvkY2MIztxb6544zu51rYkVxe7eOVIvmg9yQfvZsDrKtYirOTO3M46Up24o3/e764O0Odu7G0tVQPo9DAruYLHrxrQOg0vmOxytsx2dqN5c2pjpVtTZdYuK+X4ZSHJKOmQp0=,iv:W7RE3u9cime4aLEIhW8fIrJ554ilCNxhO5pD3wjpLhE=,tag:6uCLdwrS2MjEOJoDJqqu6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
