# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5.0@sha256:e0c87ce7df39d06b93f27cf2cc6a056611f13faaa88cc07ab4dc8bf7a85d0b11
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: &secret prowlarr-secret
        containers:
          prowlarr:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 1.37.0@sha256:aab0bfd4e96bdca19cca280a2bbf8ac60b9251dcae13459856b724a2dd3ae020
              pullPolicy: IfNotPresent
            env:
              PROWLARR__INSTANCE_NAME: prowlarr
              PROWLARR__LOG_LEVEL: info
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 600Mi
              limits:
                cpu: 500m
                memory: 1Gi
    service:
      prowlarr:
        controller: main
        ports:
          http:
            port: 9696
    ingress:
      prowlarr:
        className: internal
        annotations:
          hajimari.io/icon: cbi:prowlarr
        hosts:
          - host: &host prowlarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: prowlarr
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: prowlarr-config
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      annotations:
        secret.reloader.stakater.com/reload: *secret
