---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: &secret prowlarr-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr-develop
              tag: 1.15.0.4361@sha256:6463d232b16aa58baa6cd97807d050a54584d013784975e7015a75d4386c2e96
              pullPolicy: IfNotPresent
            env:
              PROWLARR__INSTANCE_NAME: prowlarr
              PROWLARR__LOG_LEVEL: info
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 600Mi
              limits:
                cpu: 500m
                memory: 1Gi
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: cbi:prowlarr
        hosts:
          - host: &host prowlarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      annotations:
        secret.reloader.stakater.com/reload: *secret
