# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: &secret prowlarr-secret
        containers:
          prowlarr:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.1.5@sha256:affb671fa367f4b7029d58f4b7d04e194e887ed6af1cf5a678f3c7aca5caf6ca
              pullPolicy: IfNotPresent
            env:
              PROWLARR__INSTANCE_NAME: prowlarr
              PROWLARR__LOG_LEVEL: info
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 600Mi
              limits:
                cpu: 500m
                memory: 1Gi
    service:
      prowlarr:
        controller: main
        ports:
          http:
            port: 9696
    ingress:
      prowlarr:
        className: internal
        annotations:
          hajimari.io/icon: cbi:prowlarr
        hosts:
          - host: &host prowlarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: prowlarr
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: prowlarr-config-new
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      annotations:
        secret.reloader.stakater.com/reload: *secret
