---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-lubelogger
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/lubelogger/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: database-cloudnative-pg
    - name: storage-longhorn-recurring-jobs
  interval: 30m
  retryInterval: 1m
  timeout: 3m
