---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.78.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-oauth-secret
      valuesKey: oauth-clientid
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-operator-oauth-secret
      valuesKey: oauth-clientsecret
      targetPath: oauth.clientSecret
  values:
    operatorConfig:
      logging: "debug"
    apiServerProxyConfig:
      mode: "true"
