---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    controllers:
      main:
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: paperless-ngx-secret
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.5.3
              pullPolicy: IfNotPresent
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_TIME_ZONE: US/Central
              PAPERLESS_URL: https://docs.${SECRET_DOMAIN}
              USERMAP_UID: 1000
              USERMAP_GID: 1000
              PAPERLESS_CONSUMPTION_DIR: &dirConsume /paperless/consume
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_MEDIA_ROOT: &dirMedia /paperless/media
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
              PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
              PAPERLESS_CONSUMER_RECURSIVE: true
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
              PAPERLESS_OCR_USER_ARGS: >
                {
                  "invalidate_digital_signatures": true,
                  "continue_on_soft_render_error": true
                }
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_ENDPOINT: http://127.0.0.1:9998
            envFrom: *envFrom
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.4
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
            env:
              REDIS_REPLICATION_MODE: master
            command: [ "redis-server" ]
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-minimal
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 9998
          gotenberg:
            image:
              repository: gotenberg/gotenberg
              tag: 8.0.3
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
            command:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/name: "Paperless-NGX"
          hajimari.io/icon: simple-icons:paperlessngx
        hosts:
          - host: &host docs.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host
    persistence:
      data:
        existingClaim: paperless-ngx-data
        advancedMounts:
          main:
            main:
              - path: /paperless/data
      redis:
        existingClaim: paperless-ngx-redis
        advancedMounts:
          main:
            redis:
              - path: /data
      docs:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/paperless-ngx/docs
        advancedMounts:
          main:
            main:
              - path: *dirMedia
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/paperless-ngx/consume
        advancedMounts:
          main:
            main:
              - path: *dirConsume
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 1000
