---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: database-cloudnative-pg-cluster
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.3.3
              pullPolicy: IfNotPresent
            env:
              COMPOSE_PROJECT_NAME: paperless-ngx
              PAPERLESS_TIME_ZONE: US/Central
              PAPERLESS_URL: &host docs.${SECRET_DOMAIN}
              USERMAP_UID: 1000
              USERMAP_GID: 1000
              PAPERLESS_CONSUMPTION_DIR: &dirConsume /paperless/consume
              PAPERLESS_DATA_DIR: /paperless/data
              PAPERLESS_MEDIA_ROOT: &dirMedia /paperless/media
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
              PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
              PAPERLESS_CONSUMER_RECURSIVE: true
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
              PAPERLESS_OCR_LANGUAGE: eng
          redis:
            image:
              repository: docker.io/library/redis
              tag: 7
              pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/name: "Paperless-NGX"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
            hosts:
              - *host
    persistence:
      data:
        existingClaim: paperless-ngx-data
        advancedMounts:
          main:
            main:
              - path: /paperless
      redis:
        existingClaim: paperless-ngx-redis
        advancedMounts:
          main:
            redis:
              - path: /data
      docs:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/paperless-ngx/docs
        advancedMounts:
          main:
            main:
              - path: *dirMedia
      media:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/paperless-ngx/consume
        advancedMounts:
          main:
            main:
              - path: *dirConsume
