---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-new
  namespace: default
  labels:
    app.kubernetes.io/name: &app paperless-ngx
    app.kubernetes.io/instance: *app
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis-new
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
