apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:TN12E2N3JV4QxlCmuSCr+jdAhLv7u7yifSkn28WrteE=,iv:uNnY7QomHj9+Ouo1O+7WcOew9nDIJ5mtGg/lRqw2ZJY=,tag:s30iUL4ieWSRe0tbRwdeMA==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:M028YVqIgE0R0mkHY18M9HvBUDm5VLm9b7lrYZ6xLyb14289v1Fh,iv:d8J0blk+OjYxHv2fZXmCUp6nkA1SDe8821tvPdWEEdE=,tag:Zq1QW/J7jPb2GN47P2dadw==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:dPXP1A==,iv:Tczi2qzLlaREMHSd60G3e2RTAxK5cDyJKhyT5fd56fI=,tag:CjHF8+6A+QissbiFt8PXWg==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:AZW+0yRu,iv:1PESyxHS10/vv6LavbJpQ3jZ+Sanf3ClNBo0QiaS6KI=,tag:2ABGXmX4IfZFejkVwtX8Ng==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:54f/SNW3+62xR9cB+GdgSB/m1IW1MWDYu7uvg81eKEo=,iv:KPlQ7Ne9C49cXxOhS6rAz2CmYcUOcYO30uObC+LmUSM=,tag:fzb5P0p0gvGlXbJzpAzXig==,type:str]
    RADARR__POSTGRES__MAIN_DB: ENC[AES256_GCM,data:FUBkMXKKlfIb+9E=,iv:L7kM0AkNgAAUFkjwHtOTifnznH4ZjlMJDfg251kTgYs=,tag:xvu9nM6gHlWL0dzBHbt33Q==,type:str]
    RADARR__POSTGRES__LOG_DB: ENC[AES256_GCM,data:/DMArpW4Efz1Zg==,iv:vjemAhh1csXWevB+G386bHXYoCspCkHCPB6jVklpFBg=,tag:FOZdqLWqPp7mpDUBZcRB1A==,type:str]
    #ENC[AES256_GCM,data:tOZSACkdJ2idfj6/kYE=,iv:9WssXN1HtJ7C2QVUJzy6Tk3FJgJQxoH5mqQt2DznDX8=,tag:M/e0vB4iDGU1i6R97hDXCg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bHBvmoDZC2XSwMYwtmy1X9Rk3/nUWg==,iv:eOC5NbZnosImva7+KO6Jl8NIcpHNQ1R156eGcMO/QC0=,tag:5ZiIRnOeKkBRqi76uRSTOA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:iGjGddkDSsknsZkwcLf9ziECwnkUNhvW/jHDPs2ZrnVBtWpAQu0o,iv:Sd/JZQCb5A74MHaQDrXPYHX3gK3I8zmJ6gOHMtEYBiM=,tag:ogONl47T+TD3RjBZR+Ak5w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:T7v+lNf6,iv:tQes0ZZqvrNrxXIuzLEGll/pbsBgW0aYyvHUaI7JnYg=,tag:mggJMSyJRJgR+Q7IAKTfkg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:m6fo6EWO2l42yxomSp/bBbyf2DO5uL5Ozrwr6BnyMuc=,iv:snD+ZUJKDmRAl093VS/uUDTaX/wetDdnUTzeX+Atlwc=,tag:pgiPZhQbaGsdXlNUyCCxow==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kAGrUSkxfFrQ1EdTWu8q7iC3D7Cs7ZC3gNaAUh7674f4Iw==,iv:x4EEO4wfjSmHvqKe15niJjMSCaOppFnjHxzgkebOBBg=,tag:iqTg9T77+pvFAqe1bpzi2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT2tkS0R1OWpQdlJyQWhC
            UXFIWG9xRFNXRFVmRG13ZDZiYVoyMVZlNFM4CnZxcm1oUk5iZXJXVmx4MzE1cyto
            Rng2M1czR0tBNEFVcXFEZW51eXBsL2MKLS0tIEZuU2dudDhtR1RLK1h5NTNFKzZZ
            emQ2KzAxazFwbzN3dTB1a2lmU1JsSFUKr65VR1SqVEWlkWkDtB4t6URLzVeTJN4L
            j76jKvKIcw8aNNtlvvKaAKxgjtb58d23+LLK7WyoCnmiUagKYDsIvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T17:20:10Z"
    mac: ENC[AES256_GCM,data:Wohs6tpAgLsGrnfRy89dNMOArpP8CH19utWB0ybqGKzxuINalgdhVYVkWB8SKT34Ey6PGFsbnDLnI6JljCHdyqMmfRzt9SO2f+rjxnQP4qV1/CicyqQavEcKw2hqyzCUQT+h/elQXH5Q73i1OxmahYjOuA+z2vmNe77EZCGTSgo=,iv:LTKvfEZbXm/KfWZEXoZ2LGpT0dF/O54uwzVz5Z0bw1c=,tag:ZEJyeUHT8iUbfqn0N2Mddg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
