---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iventoy-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-apps
