apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sJ85tUZrUF1GyGsvVAWLa52F8N0X3Pyj7aw=,iv:3YJxIc0nNHSSrWYkrrQsw/xGpNGMDdFVBPmo/5A63UQ=,tag:IoBt6Gi+GkkSUMr2zFsWFw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KpoWPo0PhIUzq5+mgiD606n6vm5i32Hs6jaVY89fAFb25be4,iv:b/rZ5ehGWCdZl3aJyw/8u/onuC8v/5HurQhZTGAlHio=,tag:kjUV/FTfAY51WHagDwqiUQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:pjTE+Nj+sTf3+80OAA==,iv:HUXpY0+0iObgUCT+0mP6O8LcLzBldH0A/F6tJBvP7kA=,tag:v/BEMMu4S0u411eJwWOxkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cTdVN3AzaFJFbGptTmJP
            UVdMUG9GTE1Eb2w4Z0hFQlRQMERCZ095NFdjCkRiWkVKOWNOeUozREFKTjd4L0U1
            TTYyYWN3WlVSZUoxdEZMZkRhcDErdzgKLS0tIFVPVFZKZ3BHZm1jaVB3UlJlM2t1
            a0RwTlZ2bGt3MUhlYkVlOXF1c2cvZHMK3XH2mRINEubKHiWM0dkS/308AaRMoRc0
            QunkgihC6djl5fl/F2gFEw2u43R/L415khlk2dMYwAXWQ+ZM2vSl/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T20:29:34Z"
    mac: ENC[AES256_GCM,data:5e3UG/tfsdd7UMKqT7AL7Sog9u7F+k7/NQcs2xbJoaiEX+Tr3e3I+bePqE/wsVOETXSKRq4dPX0in1NQIT25VLBBSi2C9JRmjG6T2rxygANRtXTQanKQfx37i+emBZXMtb6/L9dCMIr2aUcDI+/Oqmdq+EGMWS2yzfZDccFNQQY=,iv:KwAbySGPZZ3LkSMTKT0nZ2FTZ7Gt2c9SXrnmGHnFZw8=,tag:sw1+oteIVt+ZegbSxwNLGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
