---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-new
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: open-webui-data
  storageClassName: longhorn
