apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: default
stringData:
    #ENC[AES256_GCM,data:hkFz6oDtP+wccubAftY=,iv:rigEx6EitmItHLPsZ5Qy0ZSCGrCJY6Jl9GaP+hVqT5o=,tag:nA7bmgUKWq7o4N4YWhdmJA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:c/o5cYcmcpjJ,iv:D8zrMTCr59nCCIupIXYVy45Cps9loYX3BHD2FkCHpSU=,tag:2O/N6jIHbF1aNf48uqoEsw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kp5uNwL5ESH+cUxx4ziig12ny6qEbaQjpC3q+v/MDiKGGIobllsp3xRgpA==,iv:jhVHXjZ0y4AtQ0XV7lkbXexedF0uYB/cjmO1pN3JidA=,tag:SMCmQwsccvqJo3Z8POuByw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:O8xcxfT929Cc,iv:rMItoRPc60pj+TE3jmQxL1GqK/1OsM4NgO4UwV1DzT8=,tag:SZBhISivlldxYo2/CIBLEg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VJrhlsAwAs3CtWP3wYSt3tWkvXP0MK4hdCn0nb73e5o=,iv:qUHiqNVtba7PTOPKznQ159iX3Wip3WuyN1ocZGewM/0=,tag:Xwwu3h6mLxOT+CPVN2MHdg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2qN/z8DwxaZwrTmNDAtewjEvBWr+HyLlZIaFVGXmF9zYrA==,iv:7qIzoZaMsM2IboY19zJgFd3PahqgHk2GUusyJEOzjCo=,tag:VOuqK0kQIIShUBIaWGwEOA==,type:str]
    #ENC[AES256_GCM,data:7RJV5ydxoycdicE=,iv:zFQ/NrYCG+vCPfx8cQO9XXI8ugxIRjCAFSx26v64Wnc=,tag:KCvdt52RikN6lkaWl6h0Nw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:uyLkdjcHS0m6oc9KdUuuNggox1iJbRA5y2Tw1TQpJoSpqKKU101gVvRwXp/P1HL8IEDTOY5nqnJC9gNctOKYBObEHaCUcGVSHHcDzSMqZ9CDfMmj6yyv9QDQTgG/SWCgFAzChUvXnD9se/A7D/QWxQJ5yUCaFfi8Y/65,iv:YeVX6Ggi/R+uKuQG6dVvPyHq5o3HUkuxDxdTLKtBbs0=,tag:sdUAytBG9wLByq+Ar4HPWQ==,type:str]
    OLLAMA_BASE_URL: ENC[AES256_GCM,data:YwXi63pfulOiafzJ/acAp7NRAJKsfFo=,iv:XF36eXisaHUpI9LhDatfr0SaZqUwx8tW6cNzaBM5E90=,tag:zX4vEWYIriJIhx0S3pIMxg==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:E9JBeg==,iv:rwehzJI6Wa6NKVCar20lX/UxeR7t7Pq5kL5M0kcPvLI=,tag:YOJtFQA83wKCr3OXg06Vkw==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:oltAyUo=,iv:Iy1EU057DPUg507ByswBqRvNzn3YRYy69BoSP5X+Mqg=,tag:pkOoXVC0P1NzKA848qkvYw==,type:str]
    WEBSOCKET_REDIS_URL: ENC[AES256_GCM,data:PFZPTufX0AdtWHH9KEOjenSb7vjVBoYyQcQM87x17CoCM5K8Ur3nYl9lHsJuU5xl3w==,iv:XyKkB/qlvYrydK8UA3hvVR6Q29jy57gBZ/zoWMPV0bE=,tag:XM6wx45yZc5zq8yVtn8UsA==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:I3E4Sg==,iv:Ge4Uw6eluSyCUjHYzQ37yTfPzlop0zdEOUUib+Lxg68=,tag:ODDtuIUu5LEJW7eD2cPB+w==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:IgTE9/1WTg==,iv:PaBA7CCoCABkOV9fbPZkMeSRZTQ4JqQex0c8gRVwR8k=,tag:6v9A3K/+QjnPsnTilynOzw==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:U5iGFzxFxmRXfT+YLCblUS5mDzPN22vPogfbQ8FzOvzOphWssBWZBs3pVwLF49pG,iv:yCIeOj5o2AhJd7433gMLugD4lvBcE9WjqN+H+OyFT5w=,tag:JRRvtn+4JRti8LY7m/ZMrg==,type:str]
    username: ENC[AES256_GCM,data:caIjsCKMOZ9k,iv:cSgjSZn9TaSUhj8wiXTc8RqLSoM+WOWTkNJB6FYqNkM=,tag:3OqacefodtEWWiuZuueQiQ==,type:str]
    password: ENC[AES256_GCM,data:l7Z+RaIEwmJ6zIi9pqfMbYtptVfKrSt43v64WHOGUtI=,iv:wqM4UQqJ1Fx5/OWwTBqJQO24GZf+UQqHYacZ/hW5yMI=,tag:ApwSdKfEogtcc3yV3OtsTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM3Nqd3pidGRVVm9lMzlT
            ZWxQNkRVdnBPQVRKbnRRWCtacnpwd3gzZmpjCkJDZEVVYk1CSW9pT2xXNEZLVno3
            LzF5ejF4WkQvRkZZR0ExVndxb3JCZVUKLS0tIHVEalJmOXh3bTZsTVBKeVJZa0tk
            Z2xrWFJGVHlSWXJJYjFSTmg5ZVYvaTAKLgMFHqmHAhTFvU5b090W2JdQpwfnkxfv
            Z84VtYZhlZZCZA/gKTrAZM+jN/eMrHO9cViDsKsKQjNyptzCkABmDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T15:37:58Z"
    mac: ENC[AES256_GCM,data:j135vAagWeeJJ2mty7+DtzyTQJQXYqe1SogDB6/2KKTmJW4kRZ4kjMgBQEerd/OGsAXhceLz4bKXjJAyhBTzlR3qsL9m4af3wTAfEyDWwoJo0WLx2cI6S4hcwdVYvQQn/yX4wr7ixQpYakfEowC2MzAnzHb2dlVQCCCrUiJVpaY=,iv:bIgDgqZHzE8e72NdCqPdOqimjWdLAUoi/HZzOgJpWOA=,tag:RNcC6SfxHRKlY1mQSDs1NA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
