# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      syncthing:
        containers:
          syncthing:
            image:
              repository: syncthing/syncthing
              tag: 1.29.5@sha256:1914deddb3be7808579f3ce0eb4a1c493daa2f01e8953c2d73ba52ee2b1b418a
            env:
              PUID: "1000"
              PGID: "1000"
    service:
      syncthing:
        controller: syncthing
        ports:
          http:
            port: 8384
      listdisc:
        controller: syncthing
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.0.20.205
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP
    ingress:
      syncthing:
        className: internal
        annotations:
          hajimari.io/icon: folder-sync
        hosts:
          - host: &host sync.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: syncthing
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: syncthing-config
        globalMounts:
          - path: /var/syncthing
      data:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS
        globalMounts:
          - path: /files
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
