---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-new
  namespace: default
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: syncthing-config
  storageClassName: longhorn
