---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cnpg-superuser.sops.yaml
  - ./helmrelease.yaml
  - ./minio.sops.yaml
  - ./secret.sops.yaml
