---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: factorio
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      factorio:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          factorio:
            env:
              TZ: "America/Chicago"
              SAVE_NAME: factorio-saftb6
              BIND: "0.0.0.0"
            image:
              repository: factoriotools/factorio
              tag: stable@sha256:764ab2e97b6bd7dfbca4a8b9e25e8ca20f8dd616bd9bff104f0072073a8bc88b
              pullPolicy: IfNotPresent
    service:
      app:
        controller: factorio
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          tailscale.com/expose: "true"
          io.cilium/lb-ipam-ips: 10.0.20.206
        ports:
          gametcp:
            port: 27015
          gameudp:
            port: 34197
            protocol: UDP
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     interval: 3m
    #     scrapeTimeout: 1m
    #   prometheusRule:
    #     enabled: true
    #   exporter:
    #     env:
    #       port: 9794
    #       additionalMetrics: true
    #       unknownQueueItems: false
    persistence:
      config:
        enabled: true
        existingClaim: factorio-saftb6-data
        globalMounts:
          - path: /factorio
