apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-saftb6-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-apps
