apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-saftb6-data-new
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: factorio-saftb6-data
  storageClassName: longhorn
