# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          immich-redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.5
              pullPolicy: IfNotPresent
            env:
              REDIS_REPLICATION_MODE: master
            command: ["redis-server"]
    service:
      immich-redis:
        controller: main
        ports:
          http:
            port: 6379
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        memory: 100Mi
