---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: database  # namespace where the pvc's exist
  name: volume-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: ubuntu:jammy
          tty: true
          command: ["/bin/sh"]
          args: ["-c", "cp -r -v /mnt/old/. /mnt/new"]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          persistentVolumeClaim:
            claimName: pgbackup # change to data source pvc
        - name: new-vol
          persistentVolumeClaim:
            claimName: pvc-e8609e0f-2130-457f-9596-3529741100c5 # change to data target pvc
