apiVersion: v1
kind: Pod
metadata:
  name: pvc-manipulation-pod
  namespace: games # set this to the NS that the PVC exists in
spec:
  containers:
    - name: main
      image: debian:trixie
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      args: ["-c", "sleep 1d"]
      volumeMounts:
        - name: vol1
          mountPath: /mnt/tmp
        - name: vol2
          mountPath: /mnt/pvc
  restartPolicy: Always
  volumes:
    - name: vol1
      nfs:
        server: 10.0.0.8
        path: /mnt/AuxPool/K8S-NFS/tmp
    - name: vol2
      persistentVolumeClaim:
        claimName: factorio-saftb6-data
