apiVersion: v1
kind: Pod
metadata:
  name: pvc-manipulation-pod
  namespace: test
spec:
  containers:
    - name: main
      image: debian:bullseye
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: vol1
          mountPath: /mnt/tmp
        - name: vol2
          mountPath: /mnt/pvc
  restartPolicy: Always
  volumes:
    - name: vol1
      nfs:
        server: 10.0.0.8
        path: /mnt/AuxPool/K8S-NFS/tmp
    - name: vol2
      persistentVolumeClaim:
        claimName: mc-atm9-data
