---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: test-ubuntu-pod
  namespace: automation
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "1d"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: volume
          mountPath: /mnt
  restartPolicy: Always
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: apprise-data
