---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "1d"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: volume
          mountPath: /mnt
  restartPolicy: Always
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: nextcloud-config
