---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lubelogger
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lubelogger:
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.8
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: lubelogger-secret
        containers:
          lubelogger:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.4.6
            env:
              TZ: ${TIMEZONE}
              LC_ALL: en_US.UTF-8
              LOGGING__LOGLEVEL__DEFAULT: debug
            envFrom: *envFrom
            resources:
              requests:
                cpu: 15m
                memory: 80M
              limits:
                memory: 256M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        hosts:
          - host: 'lubelogger.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      app:
        existingClaim: lubelogger-pvc
        globalMounts:
          - path: /App/config
            subPath: config
          - path: /App/data
            subPath: data
          - path: /App/wwwroot/translations
            subPath: translations
          - path: /App/wwwroot/documents
            subPath: documents
          - path: /App/wwwroot/images
            subPath: images
          - path: /App/log
            subPath: log
          - path: /root/.aspnet/DataProtection-Keys
            subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /App/wwwroot/temp
