---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-pvc
  namespace: default
spec:
  storageClassName: longhorn-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
