# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          mealie:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.0.1@sha256:4d7542becc4f5a2a87c13f1073c974430006f56207278ade541bd93450b8fb5f
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              BASE_URL: &host recipes.${SECRET_DOMAIN}
              ALLOW_SIGNUPS: true
              API_DOCS: true
    service:
      mealie:
        controller: main
        ports:
          http:
            port: 9000
    ingress:
      main:
        className: internal
        annotations:
          hajimari.io/icon: mdi:food
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: mealie
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: mealie-config-new
        globalMounts:
          - path: /app/data
      backup:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/backups/mealie
        globalMounts:
          - path: /app/data/backups

