---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/hkotel/mealie
              tag: frontend-v1.0.0beta-5
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              # Light Mode Config
              THEME_LIGHT_PRIMARY: "#005AE6"
              THEME_LIGHT_ACCENT: "#FEBF00"
              THEME_LIGHT_SECONDARY: "#0DFC9D"
              THEME_LIGHT_SUCCESS: "#43A047"
              THEME_LIGHT_INFO: "#1976D2"
              THEME_LIGHT_WARNING: "#FF6D00"
              THEME_LIGHT_ERROR: "#EF5350"
              # Dark Mode Config
              THEME_DARK_PRIMARY: "#0097A7"
              THEME_DARK_ACCENT: "#007A99"
              THEME_DARK_SECONDARY: "#4ba3c7"
              THEME_DARK_SUCCESS: "#43A047"
              THEME_DARK_INFO: "#1976D2"
              THEME_DARK_WARNING: "#FF6D00"
              THEME_DARK_ERROR: "#EF5350"
          api:
            image:
              repository: docker.io/hkotel/mealie
              tag: api-v1.0.0beta-5
              pullPolicy: IfNotPresent
            env:
              API_PORT: "9000"
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
              TOKEN_TIME: 720 # 24 hours * 30 days
              BASE_URL: "https://recipes.${SECRET_DOMAIN}"
              AUTO_BACKUP_ENABLED: true
              ALLOW_SIGNUP: false
    service:
      main:
        ports:
          http:
            port: 3000
      api:
        controller: main
        ports:
          api:
            port: 9000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:food
        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: mealie-config
        globalMounts:
          - path: /app/data
