---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-apps
