---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config-new
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
