# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          esphome:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2024.7.2
              pullPolicy: IfNotPresent
            env:
              # ESPHOME_DASHBOARD_USE_PING: true
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      esphome:
        controller: main
        ports:
          http:
            port: 6052
    ingress:
      esphome:
        className: internal
        annotations:
          hajimari.io/icon: simple-icons:esphome
        hosts:
          - host: &host esphome.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: esphome
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: esphome-config
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
