apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: default
stringData:
    #ENC[AES256_GCM,data:XMYEuyT/rB3iMKd1jhU=,iv:ka0mElkwo6Xt3sWHMqzVKngPP6ws0u6lkwMJaXwx8rA=,tag:1O6HFM+JQRGFKO0we0YXGg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Ok+BlXHQeFzR,iv:uukve7kYKVnDVhPofJ06YjsqPQd15JsJ1hzljCCRPcQ=,tag:UqofAjVtExzmWPlQcoFrdg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tnHuKH/c5DUGm8eH47VNqg/q5Q/bhHPDxEe1Z7X6tpFUHBbS6Ic=,iv:l9CQxulacqLGuENiDp5R8ZcafcL6K5ZJlLJqaZKU0w8=,tag:PDrUZ6G9MmCEunXOIBD6ug==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tRgERbJYzxez,iv:PZh4p5/i14FREjyfUjPTTdakxu9c5hshvdfzzGEh5hk=,tag:m69m/u4ujVH3jPsr0XuBuQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:UBkBbDEgXLdNwj/Y+cHLW/YrD/2bpiSB+rdBNcVyxg8=,iv:GBc2CX/71HA7DKtrC9PWrZfeAddj0lfTuKmOLSibsRM=,tag:lyVFwB0MB4O4L7S+bJYNgQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gl4EpdvKhLnVzwC2be1yVWym+R2LlyM2SQIvVW9J2r+Dmw==,iv:3QzsUp7o6E+1WFC8TSwiL3Asvn52+9HhqmPgBouwp/A=,tag:meEqZx9fjXPPlRBFNs/FAw==,type:str]
    #ENC[AES256_GCM,data:M1QM5l1QWFN8EOY=,iv:QHKN2WxP6zNu0gV4xq5GsevsBGHv5xL7+TJ6ceyyu0I=,tag:PnbUZPRnKbowqRy3nFv3mw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:07egDkGC5p+CasdWEKoIfyLGHfrI4h5zLME03NMO/6Svggk3fOiewuXA31XjEPpaBi4Y98lSkXH+lHMhC9DQrvFJNvpsAgR4oV0BpZSHQxUeDgr7P4yPBg1I9ABAEgujmxp82FNjvZX9scdI27hmaPZtGSZLww==,iv:EzI8LLdWETrQcDvTSETDaSmGORao2UnAiOZpkRPUx/c=,tag:wZ4EkMviCdEBHjXiohaROw==,type:str]
    OLLAMA_BASE_URL: ENC[AES256_GCM,data:W25PJs+dy4ftKEIBdrhrwb/DtESI5oI=,iv:7LZnI6klZqULk7OkBiAyt8Q+9I8nl74ZPMPTyBMTHnI=,tag:HmlU0GU+U3SIhKk84QuHsA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:p+zU8g==,iv:dPLgdmx2GxHJVLYOs1GLbiP/Dn67h4ul3RIYSAvZywo=,tag:37lp3iH4qeoMH5i84ESzTA==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:gkF+AGg=,iv:kWjSEwO78PirDtvbbTpqCTsy7ZW7+Vkjp367UT9kBzM=,tag:c9ESnfOoJrGigR9BVQHaPQ==,type:str]
    WEBSOCKET_REDIS_URL: ENC[AES256_GCM,data:o0PiTPQ8b3bd0xHFHAM9FDwHJHcak2WFEO92NLZEKZkSwPX5PBqamc+TQDjp2t8B1w==,iv:N6wmOwEx8WI+iMjc6efxs+V8Gttn6UHOiTYYiddbrKY=,tag:CobfvAQRzaohkMN7k5jqoA==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:KJzThg==,iv:eWdqzPKdxEtctjQaLaoQOkFJLoImJV15d/5tvolvki4=,tag:c8JnYiPw2/WMDGUPxZOdJA==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:dHJ13OH2mQ==,iv:Dgu67R/RS++EMsS9YlM67YEJgTUZxImxpydCeUnrGhE=,tag:Z97XZYt3gaMP9Sjj1wRQJA==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:LVRKfV+kOXigevPvJTtUVuX0SC+2uPGpTJobgXx1mD4MG/Nimdv1pKAx47aUFCRY,iv:TZdzt8ddAiSh0AKTzaqwwhJxQzA2W6Fqq8lDqphtU5c=,tag:7JXXISgCdXa24m7ItbeMYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdjdxV05iWUQ4ZG1BS3I3
            VWMxUE9INFk4ZTF4c3YwVVV1L2IzVVBXb1hjClJqd2gwY1l6L3BpNFBlbDhRWmdy
            ZFFWeWltczk1SzJ2UUNpeURqVHFRK2sKLS0tIDVEaklRUDJxaWR4OWRQTTFwemlQ
            eXF0ejBOYnFyekF3REE1OGdjNUQ5cXMKbQ7AX5VvHNn78SrGcKFQYzMsmrnesSWH
            JZV2qkC33sAD+YcjRdPw7z5l+nALyjbUiACmq6bPLAwavjJZsPOOgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T01:46:43Z"
    mac: ENC[AES256_GCM,data:WImyNnhS9+9ftkDlBcaRu/h+0YB+ynXPJxtUY09Kq8AwWK8M28oSXhGR/eQnS2Cnkr4MRUha1FKIJzjTb1OWr/6IVnY+0RkdCsaAG1pwbOyZHyqyORnoljI0LjT6bUvb6xtRhQ0+Svy4FgiOUtyLOSyefOOSMU0SlaF+o+6Yfp8=,iv:DOa/r+crd1A8DzdjbELyoty/c7r9380m1AA8ZnrJIW8=,tag:2GS32Rn9bfn+PS3jTf8Zpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
