# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      lidarr:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret lidarr-secret
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5.0
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secret
        containers:
          lidarr:
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 2.13.0
            env:
              TZ: ${TZ}
              LIDARR__INSTANCE_NAME: Lidarr
              LIDARR__PORT: &port 8686
              LIDARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: *secret
    service:
      lidarr:
        controller: lidarr
        ports:
          http:
            port: *port
    ingress:
      lidarr:
        className: internal
        annotations:
          hajimari.io/icon: mdi:headphones
        hosts:
          - host: &host lidarr.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: lidarr
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: lidarr-config-new
      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/PlexPool
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 1000
