---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.2
    controller:
      strategy: RollingUpdate
    env:
      TZ: "${TIMEZONE}"
      LOG_LEVEL: "info"
      PORT: &port 80
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
      cache:
        enabled: true
        type: emptyDir
        mountPath: /app/.next/cache
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: eye-circle
        hosts:
          - host: &host requests.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *host
