---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-atm9
  namespace: games
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          mc-atm9:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: latest@sha256:0952f8d5a31213342d2e884a434432ac2ff96b17b24c1245395ad48a45b2b2fb
              pullPolicy: IfNotPresent
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  initialDelaySeconds: 240
                  exec:
                    command: ["mc-health"]
              readiness: *probes
              startup:
                enabled: false
            env:
              EULA: true
              TYPE: FORGE
              VERSION: 1.20.1
              FORGE_INSTALLER: forge-1.20.1-47.2.20-installer.jar
              FORGE_VERSION: 47.2.20
              OVERRIDE_SERVER_PROPERTIES: true
              TZ: ${TIMEZONE}
              MEMORY: 8G
              DIFFICULTY: normal
    service:
      minecraft:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.0.20.204
        ports:
          mc:
            port: 25565
    persistence:
      data:
        existingClaim: mc-atm9-data
        globalMounts:
          - path: /data
      backup:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: /mnt/AuxPool/K8S-NFS/backups/minecraft/atm9
        globalMounts:
          - path: /data/simplebackups


