apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-atm9-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-apps
